# Generated by Django 3.1.2 on 2021-03-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mail_id', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=30)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
